#!/bin/sh
# xbulk [-n] [-k] [xbps-src flags...] PKGS... - simple XBPS bulk builder

ARGS=
ARGS2=
MAKEARGS=
PKGS=

mainpkg() {
	dir=$(readlink -f srcpkgs/"$1")
	echo ${dir##*/}
}

while [ $# -gt 0 ]; do
	case $1 in
		-n|-k) MAKEARGS="$MAKEARGS $1";;
		-o|-r) ARGS="$ARGS $1 $2"; shift;;
		-a|-H|-m) ARGS="$ARGS $1 $2"; ARGS2="$ARGS2 $1 $2"; shift;;
		-*) ARGS="$ARGS $1";;
		*) PKGS="$PKGS
$(mainpkg $1)"
	esac
	shift
done

{
for pkg in $PKGS; do
	echo all: pkg-$pkg
	for dep in $(./xbps-src $ARGS2 show-build-deps $pkg |
			sed '1d;s|[<>].*$||g'); do
		mainpkg $dep |
		grep -Fx "$PKGS" |
		sed 's/^/pkg-'$pkg': pkg-/'
	done
done
printf '%s\n' pkg-%: "	pkg=\$@; ./xbps-src $ARGS pkg \$\${pkg#pkg-}"
} | make -f - $MAKEARGS
