#!/bin/sh -e
# xbump PKGNAME [git commit options] - git commit a version bump

cd $(xdistdir)

pkg=$1; shift
[ -z "$pkg" ] && pkg=$(basename $PWD)
version=$(./xbps-src show "$pkg" | sed -n '/^version/s/[^:]*:[\t]*//p')

if [ -n "$(git ls-files srcpkgs/"$pkg"/template)" ]; then
	msg="$pkg: update to $version."
else
	msg="New package: $pkg-$version"
fi

subpkg=$(xsubpkg "$pkg")
spkpattern=$(echo $subpkg | sed 's/^/^\\(/g;s/$/\\)$/g;s/ /\\|/g')
shlibs=$(git diff common/shlibs | grep "^+[^+]" | \
	sed "s/^+[^ ]\+ \(.*\)-[^-]\+_[0-9]\+$/\1/")
if [ -n "$(echo "$shlibs" | grep -v "$spkpattern")" ]; then
	echo "common/shlibs contains uncommitted changes for other packages." 2>&1
	exit 1
elif [ -n "$shlibs" ]; then
	git add common/shlibs
fi

cd srcpkgs
git add $subpkg
cd -
git commit -m "$msg" "$@"
