#!/bin/sh
# xdiff [-u|-l] [DIR] - merge/diff/list XBPS .new-* files

mergeutil() {
	vim -d "$1" "$2" && rm -vi "$1"
}

listutil() {
	printf '%s\n' "$1"
}

if [ "$1" = -u ]; then
	shift
	DIFF="diff -u"
elif [ "$1" = -l ]; then
	shift
	DIFF=listutil
else
	DIFF=mergeutil
fi

DIR=${1:-/etc}

for newfile in $(find "$DIR" -name '*.new-*_*'); do
	$DIFF "$newfile" "${newfile%.new-*_*}"
done
