#!/bin/sh
# xdiff [-u|-l] [DIR] - merge/diff/list XBPS .new-* files

XDIFF_MERGE_EDITOR=${XDIFF_MERGE_EDITOR:-vim -d}

mergeutil() {
	$XDIFF_MERGE_EDITOR "$1" "$2" && rm -vi "$2"
}

listutil() {
	printf '%s\n' "$2"
}

if [ "$1" = -u ]; then
	shift
	DIFF="diff -u"
elif [ "$1" = -l ]; then
	shift
	DIFF=listutil
else
	DIFF=mergeutil
fi

DIR=${1:-/etc}

for newfile in $(find "$DIR" -name '*.new-*_*'); do
	$DIFF "${newfile%.new-*_*}" "$newfile"
done
