#!/bin/bash
# xgensum [-f] [-i] TEMPLATE - update SHA256 sums in templates

case "$1" in
	-f) FLAG_f=$1; shift
esac

case "$1" in
	-i*) FLAG_i=$1; shift
esac

if [ -f "$1" ]; then
	template="$1"
elif [ -f "$1/template" ]; then
	template="$1/template"
else
	echo 'Usage: xgensum [-f] [-i] TEMPLATE' 1>&2
	exit 1
fi

. "$template"

XBPS_DISTDIR=$(xdistdir)
XBPS_SRCDISTDIR=$($XBPS_DISTDIR/xbps-src show-var XBPS_SRCDISTDIR | tail -1)
srcdir="$XBPS_SRCDISTDIR/$pkgname-$version"

if [ "$FLAG_f" = -f ]; then
	for f in $distfiles; do
		curfile=$(basename "${f#*>}")
		distfile="$srcdir/$curfile"
		rm -vf "$distfile"
	done
	$XBPS_DISTDIR/xbps-src -I clean $pkgname
fi

$XBPS_DISTDIR/xbps-src -I fetch $pkgname

sums=""
for f in $distfiles; do
	curfile=$(basename "${f#*>}")
	distfile="$srcdir/$curfile"
	sum=$(sha256sum $distfile)
	sums+="${sum%  *}\n "
done

sed $FLAG_i -e "/^checksum=/,/^[^ \t]/{
		/^[ \t]/d
		s/^checksum=.*/checksum=\"${sums%\n }\"/
		/^checksum=\"[^ ]*\"/s/\"//g
	}" "$template"
