#!/bin/sh
# xmindep PKGS... - minimize list of PKGS by removing implicit dependencies

rdeps() {
	for pkg; do
		xbps-query --fulldeptree -Rx $pkg
	done | xargs -d'\n' -rn1 xbps-uhelper getpkgname | sort -u
}

printf '%s\n' "$@" | grep -Fvx -e "$(rdeps "$@")" | fmt
