#!/bin/sh -e
# xnew PKG - create XBPS template template

PKG=${1?no package name given}
srcdir=$(xdistdir)/srcpkgs
shift

homepage=
version=
distfiles=
case "$PKG" in
*://*)
	# guesstimate defaults
	homepage=${PKG%/*}/
	PKG=${PKG##*/}
	ext=${PKG##*-}
	again=true
	while $again; do
		again=false
		case "$ext" in
		[0-9]*)
			version=$version${ext%%.*}.
			ext=${ext#*.}
			again=true
		esac
	done
	version=${version%.}
	PKG=${PKG%-*}
	distfiles="$homepage/\${pkgname}-\${version}.$ext"
esac

mkdir $srcdir/$PKG

cat >$srcdir/$PKG/template <<EOF
# Template file for '$PKG'
pkgname=$PKG
version=$version
revision=1
#wrksrc=
#create_wrksrc=yes
#only_for_archs="i686 x86_64"
build_style=gnu-configure
#configure_args=""
#make_build_args=""
#make_install_args=""
#conf_files=""
#make_dirs="/var/log/dir 0755 root root"
hostmakedepends=""
makedepends=""
depends=""
short_desc=""
maintainer="$(git config user.name) <$(git config user.email)>"
license="GPL-3"
homepage="$homepage"
distfiles="$distfiles"
checksum=badbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadbadb
EOF

for subpkg; do
	ln -sr -- "$srcdir/$PKG" "$srcdir/$subpkg"
	cat >>$srcdir/$PKG/template <<EOF

${subpkg}_package() {
EOF
	case $subpkg in
	*-devel) cat >>$srcdir/$PKG/template <<EOF
	depends="$PKG>=\${version}_\${revision}"
	short_desc+=" - development files"
	pkg_install() {
		vmove usr/share/man/man3
		vmove usr/include
		vmove usr/lib/pkgconfig
		vmove "usr/lib/*.a"
		vmove "usr/lib/*.so"
	}
EOF
		;;
	*) cat >>$srcdir/$PKG/template <<EOF
	pkg_install() {
		#vmove path
	}
EOF
		;;
	esac
	echo "}" >>$srcdir/$PKG/template
done

exec ${EDITOR:-vim} +3 $srcdir/$PKG/template
