#!/bin/sh
# xrecent [REPOURL|XBPS_ARCH] - list packages in repo ordered by build date

case "$(xbps-uhelper arch)" in
	*-musl)
		repo=http://muslrepo.voidlinux.eu/current/;;
	*)
		repo=http://repo.voidlinux.eu/current/;;
esac

case "$1" in
*/*)
	repo=$1;;
*-musl)	
	repo=http://muslrepo.voidlinux.eu/current/
	export "XBPS_ARCH=$1";;
?*)
	repo=http://repo.voidlinux.eu/current/
	export "XBPS_ARCH=$1";;
esac

xbps-query -M -i -R --repository=$repo -p build-date -s '' |
	sed 's/: /	/' |
	sort -t '	' -k 2 |
	column -s '	' -t
