.Dd June 25, 2019
.Dt XTOOLS 1
.Os
.Sh NAME
.Nm xtools
.Nd A collection of small utilities for use with XBPS
.Sh COMMANDS
.Bl -tag -width x
.It Nm xbarf
.Nd Display build logs of last build
.It Nm xbuildbarf Op Ar arch
.Nd Spy on current buildbot output
.It Nm xbulk Op Fl n Op Fl k Op Ar xbps-src\ flags Ar pkgs ...
.Nd simple XBPS bulk builder
.Bl -tag -offset 2n -width 2n -compact
.It Fl n
dry-run mode
.It Fl k
keep going on errors
.El
.It Nm xbump Ar pkgname Op Ar git\ commit\ options
.Nd git commit a new package or package update
.It Nm xcheckmypkgs Op Ar email
.Nd check your packages for updates
.It Nm xcheckrestart Op Fl v
.Nd list programs using outdated libraries
.Bl -tag -offset 2n -width 2n -compact
.It Fl v
verbose mode, also print the library names
.El
.It Nm xchroot Ar directory Op Ar command\ ...
.Nd chroot into a Void (or other Linux) installation
.It Nm xclash
.Nd detect file conflicts between XBPS packages
.It Nm xdbg Ar pkgs ...
.Nd list debugging packages for pkgs and recursive dependencies
.It Nm xdiff Op Fl u | l Op Ar basedir
.Nd merge/diff/list XBPS .new-* files
.Bl -tag -offset 2n -width 2n -compact
.It Fl l
list .new files
.It Fl u
print unified diffs
.El
.It Nm xdistdir
.Nd figure out
.Ev XBPS_DISTDIR
.It Nm xdowngrade Ar pkgfiles.xbps ...
.Nd install XBPS package directly from .xbps file
.It Nm xetcchanges
.Nd show diff of
.Pa /etc
against binary packages
.It Nm xgensum Op Fl f Op Fl c Op Fl i Ar template
.Nd update SHA256 sum in templates
.Bl -tag -offset 2n -width 2n -compact
.It Fl f
force (re-)download of distfiles
.It Fl c
use content checksum
.It Fl i
replace checksum in-place
.El
.It Nm xgrep Ar pattern Ar pkgs ...
.Nd search files limited to XBPS package contents
.It Nm xhog
.Nd list installed XBPS packages ordered by size
.It Nm xi Ar pkgs ...
.Nd like
.Ql xbps-install -S ,
but take cwd repo and sudo/su into account
.It Nm xilog Op Ar pattern
.Nd list installed packages by install-date
.It Nm xlg Ar pkg
.Nd open short commit log for XBPS template
.It Nm xlint Ar template | pkgname
.Nd scan XBPS template for common mistakes
.It Nm xlocate
.Oo
.Fl g | S |
.Op Fl i
.Ar pattern
.Oc
.Nd locate files in all XBPS packages
.Bl -tag -offset 2n -width 2n -compact
.It Fl g
Update a git based xlocate database, useful for local repositories
.It Fl S
Sync with the official git based xlocate database, which is recommended before using the tool
.It Fl i
Case-insensitive matching. This flag has no effect when no xlocate database is present; in that instance, matching is always case-insensitive, due to the design of
.Xr xbps-query 1 .
.El
.It Nm xlog Ar pkg
.Nd open commit log for XBPS template
.It Nm xls Ar pkg ...
.Nd list files contained in pkg (including binpkgs)
.It Nm xmandoc Ar manpage
.Nd read manpage of possibly not installed package
.It Nm xmksv Op Ar newsvdir
.Nd create new runit service templates
.It Nm xmypkgs Op Ar email
.Nd list all pkgs maintained by you
.It Nm xnew Op Fl a Ar pkg Op Ar subpkgs ...
.Nd create XBPS template
.Bl -tag -offset 2n -width 2n -compact
.It Fl a
append subpkgs to existing pkg
.El
.Pp
.It Nm xnodev
.Nd list not installed -devel packages for installed packages
.Pp
.It Nm xoptdiff Op Fl q Op Ar pkgs ...
.Nd show template options which differ from binary package
.Bl -tag -offset 2n -width 2n -compact
.It Fl q
quiet mode, show package names only
.El
.It Nm xpcdeps Ar pcfile ...
.Nd finds package matching the Requires: section of pkg-config files
.It Nm xpkg Op Fl R Ar repo Op Fl r Ar rootdir Op Fl amOHDvV
.Nd convenient package lister
.Bl -tag -offset 2n -width 2n -compact
.It Fl R Ar repo
consider only packages from
.Ar repo
.It Fl r Ar rootdir
specifies a full path for the target root directory
.It Fl a
list all packages (default: only installed)
.It Fl m
list manual packages
.It Fl O
list orphaned packages
.It Fl H
list packages on hold
.It Fl D
list installed packages not in repo
.It Fl L
list installed packages not from remote repos
.It Fl v
show version numbers
.It Fl V
show version numbers and description
.El
.It Nm xpstree
.Nd display tree view of xbps-src processes
.It Nm xq Op Fl R Ar pkg ...
.Nd query information about XBPS package
.Bl -tag -offset 2n -width 2n -compact
.It Fl R
query remote repos
.El
.It Nm xrecent Op Ar repourl | arch
.Nd list packages in repo ordered by build date
.It Nm xrevbump Ar message Ar templates ...
.Nd increase template revision and commit
.It Nm xrevshlib Ar package
.Nd list packages shlib-dependent on package or its subpackages
.It Nm xrs Ar pattern
.Nd like xbps-query -Rs, but take cwd repo into account
.It Nm xsrc Ar pkg
.Nd list source files for XBPS template
.It Nm xsubpkg Op Fl m Ar pkg
.Nd list all subpackages of a package
.Bl -tag -offset 2n -width 2n -compact
.It Fl m
only print main package
.El
.It Nm xuname
.Nd display system info relevant for debugging Void
.It Nm xvoidstrap Ar dir Op Ar packages
.Nd bootstrap a new Void installation
.El
.Sh DESCRIPTION
Tools working on the void-packages tree use
.Nm xdistdir
to find it, check that its output is reasonable first.
.Pp
.Nm xi ,
.Nm xls ,
.Nm xq
and
.Nm xrs
prefer the
.Pa hostdir
/
.Pa binpkgs
repo if you run them from a void-packages checkout.
.Sh LICENSE
.Nm
is in the public domain.
.Pp
To the extent possible under law,
the creator of this work
has waived all copyright and related or
neighboring rights to this work.
.Pp
.Lk http://creativecommons.org/publicdomain/zero/1.0/
.Sh BUGS
All bugs should be reported to
.Lk https://github.com/leahneukirchen/xtools
